// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MesaCore.Models;

public partial class Impresionesalfx
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public int? Version { get; set; }

    public DateTime? Fecha { get; set; }

    public decimal? PesoGr { get; set; }

    public decimal? Longitud { get; set; }

    public decimal? TiempoImpresion { get; set; }

    public decimal? PrecioExterno { get; set; }

    public decimal? PrecioInterno { get; set; }
}