// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MesaCore.Models;

public partial class Impresorascufx
{
    public int Id { get; set; }

    public int? ProyectoId { get; set; }

    public string Codigo { get; set; }

    public string NDibujo { get; set; }

    public string NParte { get; set; }

    public string Revision { get; set; }

    public DateTime? EntregaLaboratorio { get; set; }

    public int? Fai { get; set; }

    public DateTime? LiberacionLaboratorio { get; set; }

    public string Comentarios { get; set; }

    public string ArchivoFai { get; set; }

    public int? EstatusId { get; set; }

    public int? ClienteId { get; set; }

    [NotMapped]
    public IFormFile FormFile { get; set; }

    public virtual Clienteimpresorasfx Cliente { get; set; }

    public virtual Estatusimpresorasfx Estatus { get; set; }

    public virtual Proyectosfxcu Proyecto { get; set; }
}