// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MesaCore.Models;

public partial class Proyectosfxsal
{
    public int Id { get; set; }

    public string NombreDelProyecto { get; set; }

    public DateTime? FechaDeLaSolicitud { get; set; }

    public int? EstatusId { get; set; }

    public int? PlantaId { get; set; }

    public int? SolicitanteId { get; set; }

    public virtual Estatusproyectoimpresorasfx Estatus { get; set; }

    public virtual ICollection<Impresorasalfx> Impresorasalfx { get; set; } = new List<Impresorasalfx>();

    public virtual Plantaimpresorasfx Planta { get; set; }

    public virtual Solicitanteimpresorafx Solicitante { get; set; }
}