// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MesaCore.Models;

public partial class Solicitanteimpresorafx
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Proyectosfxcu> Proyectosfxcu { get; set; } = new List<Proyectosfxcu>();

    public virtual ICollection<Proyectosfxsal> Proyectosfxsal { get; set; } = new List<Proyectosfxsal>();

    public virtual ICollection<Registrodeimpresorasfx> Registrodeimpresorasfx { get; set; } = new List<Registrodeimpresorasfx>();
}