// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MesaCore.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Correo { get; set; }

    public string Rol { get; set; }

    public string Clave { get; set; }

    public string RefrescarToken { get; set; }

    public DateTime? FechaDeExpiracionToken { get; set; }
}